/*
Copyright 2026 The mon authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// +build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT. (manual bootstrap for Go 1.18 + shared API)

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/runtime"
)

// The methods below satisfy runtime.Object (DeepCopyObject) so the types
// can be registered with the scheme. Full deep copy logic (including for
// LabelSelector, Conditions, etc.) is elided in this bootstrap version.
// Run `make generate` with controller-gen on a modern Go toolchain for
// production deepcopy code.

func (in *GlobalFirewallPolicy) DeepCopyObject() runtime.Object {
	if in == nil {
		return nil
	}
	out := new(GlobalFirewallPolicy)
	*out = *in
	out.TypeMeta = in.TypeMeta
	// Shallow for bootstrap; real version would deep copy ObjectMeta/Spec/Status
	return out
}

func (in *GlobalFirewallPolicyList) DeepCopyObject() runtime.Object {
	if in == nil {
		return nil
	}
	out := new(GlobalFirewallPolicyList)
	*out = *in
	return out
}

func (in *ManagedCluster) DeepCopyObject() runtime.Object {
	if in == nil {
		return nil
	}
	out := new(ManagedCluster)
	*out = *in
	return out
}

func (in *ManagedClusterList) DeepCopyObject() runtime.Object {
	if in == nil {
		return nil
	}
	out := new(ManagedClusterList)
	*out = *in
	return out
}

func (in *CentralizedFirewallPolicy) DeepCopyObject() runtime.Object {
	if in == nil {
		return nil
	}
	out := new(CentralizedFirewallPolicy)
	*out = *in
	return out
}

func (in *CentralizedFirewallPolicyList) DeepCopyObject() runtime.Object {
	if in == nil {
		return nil
	}
	out := new(CentralizedFirewallPolicyList)
	*out = *in
	return out
}

func (in *ManagedHost) DeepCopyObject() runtime.Object {
	if in == nil {
		return nil
	}
	out := new(ManagedHost)
	*out = *in
	return out
}

func (in *ManagedHostList) DeepCopyObject() runtime.Object {
	if in == nil {
		return nil
	}
	out := new(ManagedHostList)
	*out = *in
	return out
}

// NOTE: This bootstrap file lets `go build ./api/...` succeed for the
// shared API package (PR1 foundation for both controller designs).
// Replace with real generated deepcopy when controller-gen is run in CI
// with a modern Go version.
