// +build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/runtime"
)

func (in *GroundRule) DeepCopyInto(out *GroundRule) {
	*out = *in
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
}

func (in *GroundRule) DeepCopy() *GroundRule {
	if in == nil {
		return nil
	}
	out := new(GroundRule)
	in.DeepCopyInto(out)
	return out
}

func (in *GroundRule) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *GroundRuleList) DeepCopyInto(out *GroundRuleList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GroundRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *GroundRuleList) DeepCopy() *GroundRuleList {
	if in == nil {
		return nil
	}
	out := new(GroundRuleList)
	in.DeepCopyInto(out)
	return out
}

func (in *GroundRuleList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// Similar for others, abbreviated for skeleton

func (in *Zone) DeepCopyInto(out *Zone) {
	*out = *in
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

func (in *Zone) DeepCopy() *Zone {
	if in == nil {
		return nil
	}
	out := new(Zone)
	in.DeepCopyInto(out)
	return out
}

func (in *Zone) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *ZoneList) DeepCopyInto(out *ZoneList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Zone, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *ZoneList) DeepCopy() *ZoneList {
	if in == nil {
		return nil
	}
	out := new(ZoneList)
	in.DeepCopyInto(out)
	return out
}

func (in *ZoneList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *ZoneRule) DeepCopyInto(out *ZoneRule) {
	*out = *in
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
}

func (in *ZoneRule) DeepCopy() *ZoneRule {
	if in == nil {
		return nil
	}
	out := new(ZoneRule)
	in.DeepCopyInto(out)
	return out
}

func (in *ZoneRule) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *ZoneRuleList) DeepCopyInto(out *ZoneRuleList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ZoneRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *ZoneRuleList) DeepCopy() *ZoneRuleList {
	if in == nil {
		return nil
	}
	out := new(ZoneRuleList)
	in.DeepCopyInto(out)
	return out
}

func (in *ZoneRuleList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *PolicyVersion) DeepCopyInto(out *PolicyVersion) {
	*out = *in
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

func (in *PolicyVersion) DeepCopy() *PolicyVersion {
	if in == nil {
		return nil
	}
	out := new(PolicyVersion)
	in.DeepCopyInto(out)
	return out
}

func (in *PolicyVersion) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *PolicyVersionList) DeepCopyInto(out *PolicyVersionList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PolicyVersion, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *PolicyVersionList) DeepCopy() *PolicyVersionList {
	if in == nil {
		return nil
	}
	out := new(PolicyVersionList)
	in.DeepCopyInto(out)
	return out
}

func (in *PolicyVersionList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *ZoneSpec) DeepCopyInto(out *ZoneSpec) {
	*out = *in
	if in.CIDRs != nil {
		in, out := &in.CIDRs, &out.CIDRs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

func (in *ZoneStatus) DeepCopyInto(out *ZoneStatus) {
	*out = *in
}

func (in *GroundRuleSpec) DeepCopyInto(out *GroundRuleSpec) {
	*out = *in
}

func (in *ZoneRuleSpec) DeepCopyInto(out *ZoneRuleSpec) {
	*out = *in
}

func (in *PolicyVersionSpec) DeepCopyInto(out *PolicyVersionSpec) {
	*out = *in
}

func (in *PolicyVersionStatus) DeepCopyInto(out *PolicyVersionStatus) {
	*out = *in
	in.CreatedAt.DeepCopyInto(&out.CreatedAt)
}
