// Code generated by hand for skeleton. In real use protoc-gen-go and protoc-gen-go-grpc.
// This provides minimal types and interfaces so the code compiles and Docker builds.

package dfwv1

import (
	"context"

	"google.golang.org/grpc"
	"google.golang.org/protobuf/types/known/emptypb"
)

type RegisterRequest struct {
	AgentId        string
	ZoneId         string
	CurrentVersion string
	Interfaces     []string
}

type RegisterResponse struct {
	AssignedZone string
}

type PolicyUpdate struct {
	Version   string
	ZoneId    string
	MapData   []byte
	Signature []byte
}

type StatusReport struct {
	AgentId string
	Version string
	Healthy bool
}

type DistributionClient interface {
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
	StreamUpdates(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (Distribution_StreamUpdatesClient, error)
	ReportStatus(ctx context.Context, in *StatusReport, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type Distribution_StreamUpdatesClient interface {
	Recv() (*PolicyUpdate, error)
	grpc.ClientStream
}

type DistributionServer interface {
	Register(context.Context, *RegisterRequest) (*RegisterResponse, error)
	StreamUpdates(*RegisterRequest, Distribution_StreamUpdatesServer) error
	ReportStatus(context.Context, *StatusReport) (*emptypb.Empty, error)
}

type UnimplementedDistributionServer struct{}

func (UnimplementedDistributionServer) Register(context.Context, *RegisterRequest) (*RegisterResponse, error) {
	return nil, nil
}
func (UnimplementedDistributionServer) StreamUpdates(*RegisterRequest, Distribution_StreamUpdatesServer) error {
	return nil
}
func (UnimplementedDistributionServer) ReportStatus(context.Context, *StatusReport) (*emptypb.Empty, error) {
	return nil, nil
}

type Distribution_StreamUpdatesServer interface {
	Send(*PolicyUpdate) error
	grpc.ServerStream
}

func RegisterDistributionServer(s grpc.ServiceRegistrar, srv DistributionServer) {}

type Distribution_ServiceDesc = grpc.ServiceDesc

func (x *PolicyUpdate) Reset()         {}
func (x *PolicyUpdate) String() string { return "" }
func (*PolicyUpdate) ProtoMessage()    {}

func (x *RegisterRequest) Reset()         {}
func (x *RegisterRequest) String() string { return "" }
func (*RegisterRequest) ProtoMessage()    {}

func (x *RegisterResponse) Reset()         {}
func (x *RegisterResponse) String() string { return "" }
func (*RegisterResponse) ProtoMessage()    {}

func (x *StatusReport) Reset()         {}
func (x *StatusReport) String() string { return "" }
func (*StatusReport) ProtoMessage()    {}
