/*
Package ebpf contains the CO-RE loader and map management for the centralized
eBPF firewall agent/controller.

This is the bootstrap implementation corresponding to PR5 in
DESIGN-centralized-ebpf-firewall-controller.md.

Real version will:
- Use bpf2go or cilium/ebpf to load firewall.bpf.c
- Implement ApplyPolicy (populate inactive buffer, flip active_idx)
- Implement RecoverOnStart using pinned maps + /var/lib/.../last_policy_version
*/

package ebpf

import (
	"fmt"
	"os"

	"github.com/cilium/ebpf"
	"github.com/cilium/ebpf/link"
	"github.com/cilium/ebpf/ringbuf"
)

// Loader manages one eBPF program + maps for a direction (ingress/egress).
type Loader struct {
	objs      *FirewallObjects // generated by bpf2go in real build
	ingressXDP link.Link
	egressTC   link.Link
	ringbuf    *ringbuf.Reader
}

type FirewallObjects struct {
	// In real build these come from //go:generate bpf2go
	XdpFirewall  *ebpf.Program `ebpf:"xdp_firewall"`
	TcEgress     *ebpf.Program `ebpf:"tc_egress_firewall"`
	GlobalConfig *ebpf.Map     `ebpf:"global_config_map"`
	// ... ordered rules 0/1, LPM, events ringbuf etc.
}

// NewLoader creates a loader (stub for now).
func NewLoader() (*Loader, error) {
	return &Loader{}, nil
}

// LoadAndAttach loads the eBPF ELF and attaches XDP + tc (bootstrap stub).
// In the real PR5+ this will use generated objects + netlink/cilium/ebpf attach.
func (l *Loader) LoadAndAttach(iface string, mode string) error {
	// TODO (PR5): load from embedded ELF or filesystem
	// prog, err := ebpf.NewProgramFromFD(...)
	fmt.Printf("eBPF loader stub: would attach XDP/tc on %s (mode=%s)\n", iface, mode)
	return nil
}

// ApplyPolicy implements the atomic double-buffer swap described in the design.
// 1. Populate the inactive set of maps from the compiled policy blob.
// 2. Flip the active_idx in the config map (single atomic update).
// 3. Write last_version file for crash recovery.
func (l *Loader) ApplyPolicy(policyVersion string, rules []byte) error {
	// rules would be the serialized compiled rules (or we materialize here).
	// See Atomic Update Code Sketch in the design doc.
	fmt.Printf("ApplyPolicy stub: version=%s, rulesLen=%d\n", policyVersion, len(rules))

	// In real code:
	// - choose inactive idx = 1 - current active
	// - bpf_map_update_batch into the inactive ordered_rules_xxx
	// - update global_config with new active_idx + rule_count + default_action
	// - fsync last_policy_version file

	_ = os.WriteFile("/var/lib/firewall-agent/last_policy_version", []byte(policyVersion), 0644)
	return nil
}

// RecoverOnStart is called on agent start / after controller outage.
func (l *Loader) RecoverOnStart() error {
	data, err := os.ReadFile("/var/lib/firewall-agent/last_policy_version")
	if err != nil {
		fmt.Println("No last_policy_version file, starting with bootstrap allow window")
		return nil
	}
	fmt.Printf("RecoverOnStart: last known policy %s (would re-attach pinned maps)\n", string(data))
	return nil
}

// Close detaches programs and closes maps.
func (l *Loader) Close() error {
	if l.ingressXDP != nil {
		l.ingressXDP.Close()
	}
	if l.egressTC != nil {
		l.egressTC.Close()
	}
	if l.ringbuf != nil {
		l.ringbuf.Close()
	}
	return nil
}
