/*
Package ebpf contains the CO-RE loader and map management for the centralized
eBPF firewall agent/controller.

This is the bootstrap implementation corresponding to PR5 in
DESIGN-centralized-ebpf-firewall-controller.md (and the detailed
"Rule Translation" and "Operating the eBPF Firewall Controller (Day-2)"
sections added later).

Key responsibilities (see design for full details):
- Receive PolicyBlob from controller (result of the 7-step compilation
  pipeline in pkg/compiler: central host resolution + agent pod materialization).
- Perform final local materialization for any symbolic pod-selector rules.
- Populate the *inactive* double-buffer (ordered_rules_v4_0/1 etc.).
- Atomic flip of active_idx in global_config.
- Write last_policy_version file + pinned last_version map for RecoverOnStart.
- Ringbuf consumption and forwarding.
- CLI surface for ops (dump-maps, test-packet, breakglass, etc.).

Real version will use bpf2go or cilium/ebpf to load firewall.bpf.c.
*/

package ebpf

import (
	"fmt"
	"os"

	"github.com/cilium/ebpf"
	"github.com/cilium/ebpf/link"
	"github.com/cilium/ebpf/ringbuf"
)

// Loader manages one eBPF program + maps for a direction (ingress/egress).
type Loader struct {
	objs      *FirewallObjects // generated by bpf2go in real build
	ingressXDP link.Link
	egressTC   link.Link
	ringbuf    *ringbuf.Reader
}

type FirewallObjects struct {
	// In real build these come from //go:generate bpf2go
	XdpFirewall  *ebpf.Program `ebpf:"xdp_firewall"`
	TcEgress     *ebpf.Program `ebpf:"tc_egress_firewall"`
	GlobalConfig *ebpf.Map     `ebpf:"global_config_map"`
	// ... ordered rules 0/1, LPM, events ringbuf etc.
}

// NewLoader creates a loader (stub for now).
func NewLoader() (*Loader, error) {
	return &Loader{}, nil
}

// LoadAndAttach loads the eBPF ELF and attaches XDP + tc (bootstrap stub).
// In the real PR5+ this will use generated objects + netlink/cilium/ebpf attach.
func (l *Loader) LoadAndAttach(iface string, mode string) error {
	// TODO (PR5): load from embedded ELF or filesystem
	// prog, err := ebpf.NewProgramFromFD(...)
	fmt.Printf("eBPF loader stub: would attach XDP/tc on %s (mode=%s)\n", iface, mode)
	return nil
}

// ApplyPolicy implements the atomic double-buffer swap described in the design
// (see "Rule Translation" section and Atomic Update Code Sketch).
//
// steps (high level):
// 1. (Caller / agent) has already performed final materialization of any
//    symbolic podSelector rules from the PolicyBlob (the 7-step compiler
//    pipeline did central host/node resolution; agent does local pod IPs).
// 2. Choose inactive buffer (1 - current active_idx).
// 3. bpf_map_update_batch the final concrete struct rule entries into the
//    inactive ordered array (and LPM/exact as decided by compiler).
// 4. Update global_config (active_idx will be flipped, plus rule_count,
//    default_action, version_hash).
// 5. Atomic flip (single u32 write to active_idx).
// 6. Persist last_policy_version file + last_version map for recovery.
// 7. Emit internal event / update metrics.
func (l *Loader) ApplyPolicy(policyVersion string, rules []byte) error {
	// rules is the final list of concrete eBPF-ready rules after full
	// translation (central + local materialization).
	fmt.Printf("ApplyPolicy stub: version=%s, rulesLen=%d\n", policyVersion, len(rules))

	// Real implementation:
	// - determine next = 1 - current
	// - populate inactive maps
	// - write config for the new active set
	// - flip
	// - fsync last_policy_version

	_ = os.WriteFile("/var/lib/firewall-agent/last_policy_version", []byte(policyVersion), 0644)
	return nil
}

// RecoverOnStart is called on agent start / after controller outage.
func (l *Loader) RecoverOnStart() error {
	data, err := os.ReadFile("/var/lib/firewall-agent/last_policy_version")
	if err != nil {
		fmt.Println("No last_policy_version file, starting with bootstrap allow window")
		return nil
	}
	fmt.Printf("RecoverOnStart: last known policy %s (would re-attach pinned maps)\n", string(data))
	return nil
}

// Close detaches programs and closes maps.
func (l *Loader) Close() error {
	if l.ingressXDP != nil {
		l.ingressXDP.Close()
	}
	if l.egressTC != nil {
		l.egressTC.Close()
	}
	if l.ringbuf != nil {
		l.ringbuf.Close()
	}
	return nil
}
